name: Keep Render Services Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # Runs every 10 minutes
  workflow_dispatch:          # Allow manual run

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Curl Precaution Service
        run: curl -s https://medical-precaution-service.onrender.com || true

      - name: Curl Disease Service
        run: curl -s https://medical-disease-service.onrender.com || true

      - name: Curl Auth Service
        run: curl -s https://medical-auth-service.onrender.com || true
